name: Reelstar
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and deploy website
        run: |
        
        
        
        
        
        
        
        Create a folder
$ mkdir actions-runner && cd actions-runner# Download the latest runner package
$ curl -o actions-runner-linux-x64-2.309.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.309.0/actions-runner-linux-x64-2.309.0.tar.gz# Optional: Validate the hash
$ echo "2974243bab2a282349ac833475d241d5273605d3628f0685bd07fb5530f9bb1a  actions-runner-linux-x64-2.309.0.tar.gz" | shasum -a 256 -c# Extract the installer
$ tar xzf ./actions-runner-linux-x64-2.309.0.tar.gz
Configure
# Create the runner and start the configuration experience
$ ./config.sh --url https://github.com/Webcomsystem/Reelstar-Node --token A6UNKAPF3TD6NLGYI3HN4BTFCPI2A# Last step, run it!
$ ./run.sh
Using your self-hosted runner
# Use this YAML in your workflow file for each job
runs-on: self-hosted

----------------------------------------------------------------------------------------------------------------------------------------------------------
without runner
--------------------------------------------------------------------------------------------------------------------------------------------

name: Deploy to AWS

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        # You'll need to add the corresponding public key to your AWS server's authorized_keys files

    - name: Deploy to AWS
      run: |
        ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/ ubuntu@13.250.135.216 "
        cd /var/www/html/take-me-backend/
        #sudo git add .
        #sudo git commit -m "servercommit"
        sudo git pull origin main"

